src/publisher/EventHubPublisher/Models/ErrorViewModel.cs
using System;

namespace EventHubPublisher.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

src/publisher/EventHubPublisher/Models/NewEventModel.cs
using System;

namespace EventHubPublisher.Models
{
	public class NewEventModel
	{
		public string Message { get; set; }

		public int EventId { get; set; }
		
		public Guid CorrelationId { get; set; }

		public DateTime EventTime { get; set; }
	}
}

src/publisher/EventHubPublisher/Controllers/EventManagerController.cs
using System.Threading.Tasks;
using EventHubPublisher.Managers;
using EventHubPublisher.Models;
using Microsoft.AspNetCore.Mvc;
using Mx.EventHub.Model;

namespace EventHubPublisher.Controllers
{
    public class EventManagerController : Controller
    {
	    private readonly IEventHubManager _eventHubManager;

	    public EventManagerController(IEventHubManager eventHubManager)
	    {
		    _eventHubManager = eventHubManager;
	    }
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Create()
        {
	        return View();
        }


        [HttpPost]
        public IActionResult Create(NewEventModel newEventModel)
        {
	        return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> CreateEventTypeOne()
        {
	        await _eventHubManager.SendEventAsync(new EventMessageModel("Event Type One Created"))
		        .ConfigureAwait(false);
			
	        return RedirectToAction("Create");
		}

        [HttpPost]
        public async Task<IActionResult> CreateEventTypeTwo()
        {
	        await _eventHubManager.SendEventAsync(new EventMessageModel("Event Type Two Created"))
		        .ConfigureAwait(false);

			return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> CreateEventBatch()
		{

			var eventBatch = new EventMessageModel[]
			{
				new EventMessageModel("Batch Event One Created"),
				new EventMessageModel("Batch Event Two Created"),
				new EventMessageModel("Batch Event Three Created")
				,new EventMessageModel("Batch Event Four Created")
			};
	        await _eventHubManager.SendEventsAsync(eventBatch)
		        .ConfigureAwait(false);

	        return RedirectToAction("Create");
		}
	}
}

src/publisher/EventHubPublisher/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EventHubPublisher.Models;

namespace EventHubPublisher.Controllers
{
    public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}


		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

src/publisher/EventHubPublisher/Views/EventManager/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create An Event</h2>

<div>
    <div class="form-group">
        <form asp-action="CreateEventTypeOne">
            <input type="submit" class="btn btn-primary form-control" value="Create Event Type 1"/>
        </form>
    </div>
    <div class="form-group">
        <form asp-action="CreateEventTypeTwo">
            <input type="submit" class="btn btn-primary form-control" value="Create Event Type 2"/>
        </form>
    </div>
    <div class="form-group">
        <form asp-action="CreateEventBatch">
            <input type="submit" class="btn btn-primary form-control" value="Create Event Batch"/>
        </form>
    </div>
</div>

src/publisher/EventHubPublisher/Views/EventManager/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<a asp-action="Create" asp-controller="EventManager" class="btn btn-prmary">Create Event</a>

src/publisher/EventHubPublisher/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Event Hub Testing

src/publisher/EventHubPublisher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventHubPublisher</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EventHubPublisher</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="EventManager" asp-action="Index">Event Management</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EventHubPublisher</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>